services:
  - type: web
    name: bert-sentiment-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=$PORT
    plan: free
    envVars:
      - key: TRANSFORMERS_CACHE
        value: ./transformers_cache
      # The PORT variable is automatically set by Render, so it's usually not needed
      # - key: PORT
      #   value: "10000"  # Can be omitted as Render will provide the PORT
